POST http://localhost:3001/videos
Content-Type: application/json

{
    "title": "Video node",
    "description": "Description 01",
    "duration": 190
}

###
# GET http://localhost:3001/videos?search=node
GET http://localhost:3001/videos

###
PUT http://localhost:3001/videos/615c1bae-b210-40a3-9235-b5bb199f00bd
Content-Type: application/json

{
    "title": "Video06",
    "description": "Description 06",
    "duration": 10
}

### 
DELETE  http://localhost:3001/videos/615c1bae-b210-40a3-9235-b5bb199f00bd
