POST https://kn-node-do-zero.onrender.com/videos
Content-Type: application/json

{
    "title": "Video node02",
    "description": "Description 0102",
    "duration": 190
}

###
# GET https://kn-node-do-zero.onrender.com/videos?search=node
GET https://kn-node-do-zero.onrender.com/videos

###
PUT https://kn-node-do-zero.onrender.com/videos/615c1bae-b210-40a3-9235-b5bb199f00bd
Content-Type: application/json

{
    "title": "Video06",
    "description": "Description 06",
    "duration": 10
}

### 
DELETE  https://kn-node-do-zero.onrender.com/videos/615c1bae-b210-40a3-9235-b5bb199f00bd
